### ISSUE TITLE
improve payout key handling

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#12]
We need to decide how to get keys for the payout transaction.

.env vars - current approach
Hashicorp vault - (similar risk footprint, but keys not laying there in config files)
Support ledger (not viewed as pracitcal since a) time consuming and b) lots of repetitive user input)
Generate ephemeral keys
??
 
Alternatively, we could generate a simple mina client send-payment script if we can assume an online node for payment processing - see https://github.com/jrwashburn/mina-pool-payout/issues/6

**Comment by jrwashburn** [comment]
Decided to implement ephemeral keys approach; so we support a) ephemeral keys or b) keys provided in .env

**Comment by mnguyen-io** [comment]
just a question in regards to keys provided. The following command gives me a 52 char priv key:

mina advanced dump-keypair --privkey-path keys/my-payout-wallet

However, the coda-sdk is expecting 58 characters. Any ideas which it should be?

```
  DT { t: 0, c: 'Private key', l: 11 } ]
[ 0,
  [ 248,
    DT { t: 0, c: 'Base58_check.Invalid_base58_character', l: 37 },
    352 ],
  DT { t: 0, c: 'Private key', l: 11 } ]

```


```
$ mina advanced dump-keypair --privkey-path test
Private-key password: 
Public key: B62qkHHp9SyYeZRu3GpWfvTMwvPtyt8sBxQQc7AMyAEL9wa49JTegUJ
Private key: EKFBcwGHPY1VGUbWm2X2hcbaNx53picis2HrK7iewAQke1TrPGPw
```

**Comment by jrwashburn** [comment]
Deleted content from your post; I think it is okay at 52 characters long -- but should be base58 alphabet. I just deleted the value and didn't try to compare it -- it should not be posted. The only valid characters should be: `123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz`, and that error seems to indicate that an invalid character was used/provided - not sure. But mine is also 52 chars. I have not tested with exported keys, I will try to do that and update -- probably tomorrow.

**Comment by mnguyen-io** [comment]
Sorry - you can ignore my comment/question. When I used the sample.env there were "" included in the parameters for SEND_PUBLIC_KEY and SEND_PRIVATE_KEY which I thought meant I should just throw my keys in between the quotes, but it looks like when this is done the quotations become apart of the KEYs and hence the Invalid_base58_character.

**Comment by jrwashburn** [comment]
We’ll remove the quotes – that is confusing. Good catch.

On 3/14/21, 8:56 AM, "Michael Nguyen" ***@***.******@***.***>> wrote:


Sorry - you can ignore my comment/question. When I used the sample.env there were "" included in the parameters for SEND_PUBLIC_KEY and SEND_PRIVATE_KEY which I thought meant I should just throw my keys in between the quotes, but it looks like when this is done the quotations become apart of the KEYs and hence the Invalid_base58_character.
