### ISSUE TITLE
Support hard fork with no supercharged rewards

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#138]
The current calculator is over complicated vs. what is needed once supercharged awards are gone.

If processing on Fork 1, use a new calculator that does not include supercharged rewards.

**Comment by artem-staked** [comment]
Hey @jrwashburn ! First, thanks for all your hard work on this project!

We recently met this error for the first time `NPS Share must be equal to total staked amount`

I've added debug strings and I see for some runs we get values like:
```
sumEffectiveNPSPoolStakes : 2796257.8051219704
totalStake:  2796257.80512197
```
and for others 
```
sumEffectiveNPSPoolStakes : 2796257.80512197
totalStake:  2796257.80512197
```

Do you know if this fix you're going to merge will fix this too?

**Comment by jrwashburn** [comment]
@artem-staked are you using api.minastakes.com as a data source, or something else?

**Comment by jrwashburn** [comment]
For context, asking because this: https://github.com/jrwashburn/mina-payouts-data-provider/pull/54 plus this: https://github.com/jrwashburn/mina-pool-payout/pull/137 (both have been merged and deployed to the api) should have resolved this issue. Please pull the latest if you have not already. And if you are running on latest, please send me your pool key and I'll run through the debugger to identify any lingering issue.

**Comment by artem-staked** [comment]
Yeah, api as the source. And I've just noticed I was not on the latest version. I was going here to delete my comment, but you turned to be faster:) Sorry for bothering you
