### ISSUE TITLE
Support dual classes of pool shares with differing payout rules

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#21]
Edited based on new O1 rules. This is now mandatory and requires a substantial change to the pooling approach.

- Mina Foundation and O(1) Labs are delegating their stake to block producers; however, they have a restriction on fee percentages of 5%. Several pool providers have higher pool fees, and need to support charging a differentiated fee for "normal" balances vs. foundation and O(1) balances. 
- Many pools include delegations from locked accounts, whose owners will not want their share paid back to the locked account, but to another unlocked account to increase the potential for supercharged coinbase.
- Some pool operators also delegate to themselves, and may not want to payout their share, but leave it in the coinbase-receiver wallet.  

#### New Payout Rules
The new payout rules will need 2 classes of "shares" plus the pool operator, with a payout waterfall that implements the following:

##### Non-Participating shares
- o(1) labs delegators
- mina foundation delegators
- do not participate in supercharged awards
- do not participate in fees
- do not pay fees
- expect 0.95 * share * regular coinbase for each block produced by the pool
[Official rules here](https://minaprotocol.com/docs/advanced/foundation-delegation-program)
- pay special attention to the requirement to include discord id in payout to foundation/o1 (created issue #35 for that, but it must be released with this.)

##### Common Pool
- after preferred shares are paid and BP fee on those is deducted 
- receives all transaction fees, pays all snark fees, receives coinbase remaining after NPS payout
- calculate remaining weighted share basis including supercharged allocation

##### Pool Operator
- charges 0.05 on each Non Participating share payout
- charges configured Pool Fee on each Common payout

#### Other requirements
- Do all math in nanomina, and round down after each division or multiplication to truncate fractional nanomina.
Note the dust and output at the end as a dust amount?
- Determine whether a coinbase amount is supercharged or not by checking if the WinnerKey is unlocked. If coinbase is supercharged, NPS get 1/2 of that amount in the NPS portion of the calculation.

#### Future support:
- Just FYI - each staking key should be able to specify a payout-address, which would cause the pool to send their payouts to a different address (see #33 , #34 )

##### Pool Operation Decisions / Consider for parameterization
- Share NPS portion of super-charged blocks with common pool?
- Charge NPS portion of fees to Common pool or separate for operator to pay from foundation delegation?

Suggested output 

| mina-pool-payout | date time |
| --- | --- | 
| Calculating pool payout from blocks | X to Y | 
| Pool canonical blocks | B1, B25*, B36, B532 (add a * to supercharged blocks) | 
| Total coinbase generated | C |
| Total transaction fees | F |
| Total snark costs | S (include snark + fee via coinbase) | 
| Total Non Participating Shares Payout | P(nps) |
| Total Common Shares Payout | P(c) | 
| Total pool dust | D | 

Planned Payout:
| Total Gross Mina Generated by Pool | Amount nanomina | Amount mina |
| --- | --- | --- |
| B62.... | Amount nanomina | Amount mina |
| B62..... | Amount nanomina | Amount mina |
| TOTAL Payout: | Amount nanomina | Amount mina |
| Pool Remainder | Amount nanomina | Amount mina |
| Total Payout + Remainder | Amount nanomina | Amount mina |
```
Confirm Payouts, and if correct and necessary, send funding amounts as instructed below.
Then re-run with this payout with process payout command below to send payouts.

Ledger Funding Command:
mina_ledger_wallet send-payment --offline --network testnet --nonce FUNDERNONCE --fee 0.1 BIP44ACCOUNT FUNDING_FROM_ADDRESS ...

Mina Client Funding Command:
mina client send-payment --amount TOTAL --receiver PAYORKEY --sender TBDYOURFUNDINGACCOUNT --fee 0.1

Process Payout Command:
npm run  ...  --hash aADesdf234sadFASDFsdfdFASDFASDF
```

**Comment by kobigurk** [comment]
I like the `fee_override.json` approach.

**Comment by jrwashburn** [comment]
> I like the `fee_override.json` approach.

Maybe I should have just closed the old issue, but here it is, repurposed.
