### ISSUE TITLE
Add getRecommendedFee function

### ISSUE THREAD

**Issue by bennoll** [jrwashburn/mina-pool-payout#24]
_Per @jrwashburn [comment on PR 23](https://github.com/jrwashburn/mina-pool-payout/pull/23#discussion_r593832012):_

Rather than use a `SEND_TRANSACTION_FEE` environment variable, add a `getRecommendedFee` function to: 

1. Calculate a recommended fee
2. Decide whether the fee is paid by the pool or by the staker.

**Comment by jrwashburn** [comment]
This may provide a simple solution. an API version of this: https://feenow.minascan.com/ is available here: 
https://api.minascan.com/v1/transaction/fee ->
{"code":200,"data":{"rapid":10000000,"fast":10000000,"standard":10000000,"slow":1000000,"timestamp":1617205923}}

Suggest implementation provide a governor (min/max) to prevent surprises based on sparse data or temporary issues.

Publisher requests a utm_source of appname as well, suggest that be a .env param as well. (e.g. https://api.minascan.com/v1/transaction/fee?utm_source=PoolNameFromEnv)

Also let pool owner configure fast, standard, or slow fee...
