### ISSUE TITLE
Confirmations not being applied

### ISSUE THREAD

**Issue by garethtdavies** [jrwashburn/mina-pool-payout#3]
It always goes to the latest height despite changing values of k.

i.e. specify `K=290` and when the current height is 679 it gives this:

`This script will payout from blocks 0 to 679` so not correctly stopping at height 359. 

As an aside I renamed this variable to confirmations as some producers might want a value of say 100 confirmations etc... and `k` has a specific meaning.

**Comment by garethtdavies** [comment]
Ah I see this commented out. I'll leave this open in any case maybe to consider changing to confirmations.

**Comment by jrwashburn** [comment]
K is added back -- I had commented it out while testing on a short chain.

I renamed it to finalityHeight - I thought that was more explicit. Major refactor in process -- now that we are calculating the same numbers we're going to deviate in structure and name. Hopefully the rules/algo don't change again so we don't have to compare. WIP on branch refactor-payouts if you want to follow.

**Comment by jrwashburn** [comment]
I like confirmations better than hard configuring K or going to graphql to get K at runtime. If someone wants to run ad 10 or 80 confirmations instead of K, that should be okay. 

Added to refactor PR https://github.com/jrwashburn/mina-pool-payout/pull/5 along with other .env cleanup. 

Closing.
