### ISSUE TITLE
payout calculations when spanning multiple staking ledgers

### ISSUE THREAD

**Issue by mnguyen-io** [jrwashburn/mina-pool-payout#31]
Wonder if there are any plans to implement logic to take into account that MIN_HEIGHT + MAX_HEIGHT might span multiple ledgers and therefore staking/rewards number may vary.

Example:

MIN_HEIGHT = 100
MAX_HEIGHT = 1000

If blocks 100 - 500 belongs to one staking ledger where X amount is delegated to a pool

Let's say delegator increases/decreases their delegation amount which is reflected in the next staking ledger and the transition from the previous staking ledger to the next occurred at block 501. Then rewards calculated for blocks 100-500 would differ from those at 501-1000.

Unless I am mistaking something here

**Comment by jrwashburn** [comment]
Yes, that is implemented already. We first get the blocks to be processed, then get the appropriate list of ledger hashes. 
Currently at lin 50 in index
 const ledgerHashes = [...new Set(blocks.map(block=>block.stakingledgerhash))];

We expect a file named [hash].json to be present which should contain the relevant staking ledger. We're making several other changes this week to implement the new foundation rules, and then will include more info on these expectations in the readme.
