### ISSUE TITLE
Separate payout address for pool operator

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#33]
Pool operators should have their coinbase receiver delegating back to their block producer, and will want to either a) leave their funds on the coinbase-receiver cold wallet, or else b) send them to yet another account. It will not make sense to incur fees to move the pool's share from the cold wallet to the payout wallet, only to move them back again to the same cold wallet.

Operators should be able to either:
1) leave pool shares on the cold wallet - and generate an alternate funding template command reduced by the amount of the pool shares, and do not payout the portion of fees for the pool operator (they will simply be retained where they are); or
2) configure a separate pool operator account where the pool fees/remainder will be sent.

**Comment by jrwashburn** [comment]
Option 2 may just be an ordinary case of #34

**Comment by lampardlb** [comment]
Exactly. For instances I have 3 wallet delegating to the hot wallet, and I do not need the rewards to be sent back to them. Could you add the feature to allow excluding certain addresses from payments please? Thanks.

**Comment by jrwashburn** [comment]
Now supported via configuration in src/data/.substitutePayTo file - see readme for more information.
