### ISSUE TITLE
Allow for signing transactions without broadcasting

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#38]
from https://github.com/jrwashburn/mina-pool-payout/pull/30#issuecomment-803512110

Do we have an option to just sign it without broadcast? I think we can add a variable on the .env file to let users can choose just signing or both signing and broadcasting

**Comment by jrwashburn** [comment]
Will not implement; checking transactions can be displayed in the table, or previewed in the files.

**Comment by vanphandinh** [comment]
> Will not implement; checking transactions can be displayed in the table, or previewed in the files.

How can do that when generating the transaction detail files and broadcasting tx doing at the same time?

**Comment by jrwashburn** [comment]
You must provide the hash of a calculation-only run in order to broadcast, so you run it once, check the result, then run again with the hash from the first run to actually send.

________________________________

**Comment by vanphandinh** [comment]
> You must provide the hash of a calculation-only run in order to broadcast, so you run it once, check the result, then run again with the hash from the first run to actually send.
> […](#)

Okey bro, so re-merge my old PR when you’re ready.
