### ISSUE TITLE
Delay the tiny payments until the next epoch

### ISSUE THREAD

**Issue by vanphandinh** [jrwashburn/mina-pool-payout#44]
**Problem:** The pool will receive many delegations with different amounts of mina tokens. But if the delegated mina amount of a user is too small, then the reward received will be very small as well, maybe some will less than the tx fee.

**Solution:** Set up a minimum payout threshold, so if the payment is greater than or equal to it, it will be paid, if not, delay it until the next epoch.

**Comment by jrwashburn** [comment]
Reopening - we definitely want/need the feature at some point!

**Comment by jrwashburn** [comment]
In the meantime, we now have #55 to simply suppress the payouts.
