### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by hsq125** [jrwashburn/mina-pool-payout#56]
`npm run payout -- -m=0 -x=1000`

gives the following error

mina@cs3:~/mina-pool-payout$ npm run payout -- -m=0 -x=1000

> mina-payout@1.0.0 payout /home/mina/mina-pool-payout
> ts-node -r dotenv/config src/index.ts "-m=0" "-x=1000"

/home/mina/mina-pool-payout/src/core/send-payments.ts:69
    return data.account.inferredNonce ?? 0;
                                       ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module.m._compile (/home/mina/mina-pool-payout/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/mina/mina-pool-payout/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mina/mina-pool-payout/src/index.ts:6:1)

content of debug file is 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'payout',
1 verbose cli   '--',
1 verbose cli   '-m=0',
1 verbose cli   '-x=1000' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prepayout', 'payout', 'postpayout' ]
5 info lifecycle mina-payout@1.0.0~prepayout: mina-payout@1.0.0
6 info lifecycle mina-payout@1.0.0~payout: mina-payout@1.0.0
7 verbose lifecycle mina-payout@1.0.0~payout: unsafe-perm in lifecycle true
8 verbose lifecycle mina-payout@1.0.0~payout: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/mina/mina-pool-payout/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle mina-payout@1.0.0~payout: CWD: /home/mina/mina-pool-payout
10 silly lifecycle mina-payout@1.0.0~payout: Args: [ '-c',
10 silly lifecycle   'ts-node -r dotenv/config src/index.ts "-m=0" "-x=1000"' ]
11 silly lifecycle mina-payout@1.0.0~payout: Returned: code: 1  signal: null
12 info lifecycle mina-payout@1.0.0~payout: Failed to exec payout script
13 verbose stack Error: mina-payout@1.0.0 payout: `ts-node -r dotenv/config src/index.ts "-m=0" "-x=1000"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mina-payout@1.0.0
15 verbose cwd /home/mina/mina-pool-payout
16 verbose Linux 5.4.0-73-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "payout" "--" "-m=0" "-x=1000"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error mina-payout@1.0.0 payout: `ts-node -r dotenv/config src/index.ts "-m=0" "-x=1000"`
22 error Exit status 1
23 error Failed at the mina-payout@1.0.0 payout script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

I had these files in the path
total 7.9M
drwxrwxr-x   5 mina mina 4.0K Jun  3 14:50 .
drwx------   9 mina mina 4.0K Jun  3 14:53 ..
-rw-rw-r--   1 mina mina  948 Jun  3 14:09 .env
drwxrwxr-x   8 mina mina 4.0K Jun  3 13:56 .git
-rw-rw-r--   1 mina mina   76 Jun  3 13:56 .gitignore
-rw-rw-r--   1 mina mina 1.1K Jun  3 13:56 LICENSE
-rw-rw-r--   1 mina mina 9.7K Jun  3 13:56 README.md
-rwxrwxr-x   1 mina mina  479 Jun  3 14:37 export_ledgers.sh
-rw-r--r--   1 mina mina 2.1M Jun  3 14:38 jwJXdYzAikMHnTsw2kYyS1WQxJrGQsy1FKT5c18eHP2wGANafKf.json
-rw-r--r--   1 mina mina 1.8M Jun  3 14:38 jxVF5YbC3B5Rk6ibfsL97WaqojfxrgWtEqMJST9pb4X8s3kRD2T.json
-rw-r--r--   1 mina mina 2.1M Jun  3 14:38 next-epoch-ledger.json
drwxrwxr-x 190 mina mina  32K Jun  3 14:16 node_modules
-rw-rw-r--   1 mina mina  77K Jun  3 14:16 package-lock.json
-rw-rw-r--   1 mina mina  898 Jun  3 14:16 package.json
-rw-rw-r--   1 mina mina  899 Jun  3 13:56 sample.env
drwxrwxr-x   5 mina mina 4.0K Jun  3 13:56 src
-rw-r--r--   1 mina mina 1.8M Jun  3 14:38 staking-epoch-ledger.json
-rw-rw-r--   1 mina mina  388 Jun  3 13:56 tsconfig.json

**Comment by jrwashburn** [comment]
This looks like you are not running the correct version of node - node 14 is a dependency.

**Comment by hsq125** [comment]
I was still on Node 10. Upgraded to 14 and it works now.

Sorry for that.

(and by the way : thanks for the tool!)
