### ISSUE TITLE
RFC: production pipeline for pool payouts

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#6]
We need to make several assumptions about the preferred runtime environment, balancing ease of operations and security. With online access to a running node and keys, we could fully automate the pipeline for pool payouts including signing and payments. On the opposite end to support fully offline signing, there may be 2-3 steps involved with sneakernet, etc. Middle ground approaches may include private network communications; however, we tend to think those are nearly as vulnerable as fully online access.

We'd like to get feedback from the pool operator community on the proposed process overall, feedback on how you would like to see the dependencies managed (e.g. data sources to support, etc.,) and specifically your current thinking and plans for on-line vs. offline node for transaction generation and signing,

Dependencies that the pool payout algorithm requires include:

1) staking ledger - currently expecting a json file from:
```coda ledger export staking-epoch-ledger```

2) postgres mina-archive database - read access to the following tables in an archive db: public_keys,  blocks, internal_commands, blocks_internal_commands, user_commands, and blocks_user_commands.

3) storage - write access to some storage option - database or files TBD. The process needs to write out the payout calculations and track the last block processed. We are leaning toward json files for this.

Downstream dependencies:

4) payout signing - after calculating the payouts, transactions need to be generated and signed. We assume this will be an offline operation to support ledger signers, etc. This is probably the most important decision to make re: online vs. offline requirements. This requires access to keys in some form.

5) payout broadcast - after generating and signing transactions, they need to be broadcast to the network. This requires an online node.

**Proposed pipeline:**
1. Pool operators are expected to provide .json files for the staking ledgers. This would need to be updated for each epoch. To avoid timing issues, support will be added for the current and next staking epoch ledgers. Files should be provided at least every epoch.

2. Payout app execution will output 3 files, the third file (C) would only be created if run with "commit" mode 
A. write payout details in payout_details_[ccyymmddhhmmss]_[lastBlockHeight].json - this will provide an audit trail for the payout calculations
B. write payoutJson to payout_transactions_[ccyymmddhhmmss]_[lastBlockHeight].json - this would be then copied (sneakernet, admin network?) to the transaction signer node.
C. write a control file to log last block processed. payout_control.json append-only {payoutDetails: hash, payoutTransactions: hash, lastBlockProcessed: blockHeight}

File C will become a dependency for future runs as the payour will process from lastBlockProcessed heigh to the current chain height. More safe versions may include a signed control file returned from the payout transaction generator so that the payout script can trust the height was processed.

3. Pool operators will (TBD) copy payout_transactions json and payout_control file to transaction gen/signer node if separate.

4. Run transaction gen/sign process (WIP) - optionally sign control file to return to payout calculator.

5. Copy ouptut file(s) from transaction gen/sign to node to broadcast transactions.

3-5 could be automated -- IF you are willing to have an online signer.

**Comment by Comdex** [comment]
If we rely on the data source of an archive node, and we can specify the time interval for computation, then the json of staking ledger for every epoch wouldn't be necessary, right ？

**Comment by jrwashburn** [comment]
We will still want the staking ledger. (Hopefully, it will make its way into the archive db structure.) I would not want to recalculate all the stakes/delegation for each epoch -- that's already done "officially" so we would want to use that. Since it changes every epoch after the 1st, we will need it updated. If you mean we don't need it historically for every epoch in the past, that is true once it has been processed. I would plan on saving it for record-keeping and audit purposes.

**Comment by Comdex** [comment]
Yes, I also hope the staking ledger will make its way into the archive db structure, but I  just hope it won't be necessary for every epoach to export staking ledger. I'm fine with all the other proposals. I'm inclined to manually distribute the bonus and generate the signature offline.

**Comment by jrwashburn** [comment]
> Yes, I also hope the staking ledger will make its way into the archive db structure, but I just hope it won't be necessary for every epoach to export staking ledger. I'm fine with all the other proposals. I'm inclined to manually distribute the bonus and generate the signature offline.

I was thinking that we could have the calculator connected to a node and get the ledger itself. It has to be somewhat online anyway because it must talk to the archive db -- so maybe it's okay to also let it fetch the staking ledgers. I didn't really like the idea because it would need to ssh as the staking ledger isn't in the graphql interface. Probably better to just add a script that runs on the node and dumps the staking ledgers every 24 hours and sends them out from the node to a shared storage location. 

Is your primary concern around automation and does a simple shell script on the node that sends the ledgers out solve that well enough?

Maybe worth requesting those exports to be signed by the generator so that we can trust them as well....

**Comment by lampardlb** [comment]
Just out of curiosity - this method here requires a running archive node, which I suppose would remove the dependence on getting data from other sources. But all the data will be available on the GraphQL of the explorer, right? If I'm not concerned with the dependence - which I suspect many of the BPs are not - won't it be easier to query the explorer, get the data and do the calculation quickly? Thanks.

**Comment by jrwashburn** [comment]
We intend to add multiple data providers for the typescript version - so you could choose archivedb, minaexplorer, or figment data sources.

**Comment by lampardlb** [comment]
> We intend to add multiple data providers for the typescript version - so you could choose archivedb, minaexplorer, or figment data sources.

That's great news, thanks

**Comment by Comdex** [comment]
> > Yes, I also hope the staking ledger will make its way into the archive db structure, but I just hope it won't be necessary for every epoach to export staking ledger. I'm fine with all the other proposals. I'm inclined to manually distribute the bonus and generate the signature offline.
> 
> I was thinking that we could have the calculator connected to a node and get the ledger itself. It has to be somewhat online anyway because it must talk to the archive db -- so maybe it's okay to also let it fetch the staking ledgers. I didn't really like the idea because it would need to ssh as the staking ledger isn't in the graphql interface. Probably better to just add a script that runs on the node and dumps the staking ledgers every 24 hours and sends them out from the node to a shared storage location.
> 
> Is your primary concern around automation and does a simple shell script on the node that sends the ledgers out solve that well enough?
> 
> Maybe worth requesting those exports to be signed by the generator so that we can trust them as well....

Yes, I would like to be able to automatically capture and back up the ledger data for each epoch, and then I can hand out rewards at any agreed time frame, and of course verify the correctness of the calculations from multiple sources

**Comment by jrwashburn** [comment]
Perhaps we should generate unique payout keys for each payout - so you have a one-time use disposable wallet that is generated for the payout. The downside is it costs one mina each time. The upside is we can generate signing keys. That pipeline would be:

Get staging ledgers
Run pool payout which includes:
 - Process blocks
 - Generate payout key
 - Generate & sign transactions to send from payout key
Generate (probably using ledger) transaction to send mina to the new payout key (+1 mina to create the account)
Copy all signed files over to the live node to broadcast - sending the mina to the payout key first.

The benefit of this approach is that the private key is ephemeral and doesn't exist outside of the process so it's much more secure, and you can use a ledger or whatever you want to supply mina to the payout key.

**Comment by jrwashburn** [comment]
> Perhaps we should generate unique payout keys for each payout - so you have a one-time use disposable wallet that is generated for the payout. The downside is it costs one mina each time. The upside is we can generate signing keys. 
...
> The benefit of this approach is that the private key is ephemeral and doesn't exist outside of the process so it's much more secure, and you can use a ledger or whatever you want to supply mina to the payout key.

After further discussion/understanding, this is a bad idea. It burns relatively precious ledger account space on top of the extra mina costs. It is worth keeping for testnets to keep things simple (don't have to track nonces) but this should not be used  for mainnet. Will update readme to that effect.

**Comment by jrwashburn** [comment]
Given that the pool payout requires _some_ online access, I am proposing this as the reference approach:

1. Run mina-pool-payout on a regular node. This provides several benefits, including: 
- could get the nonce for a payout address
- access staking ledgers without copying files around
- could validate the hash of the staking ledger (I'm sure we could find the hash algo so this is just lazy)
- could just use the hot BP wallet to sign and send the payouts (low risk since it would only get funded by an offline signed transaction for that payout, and the hot wallet is already "exposed" on the bp node anyway.

2. Manually generate and sign an offline transaction to fund the hot wallet. We could generate the commands in the mina-pool-payout run for either approach, although I suspect it will be easier to just do this manually since you'll want to sign and verify manually anyway.

3. Copy offline signed transaction via usb drive to middleman node, send via public gateway, or upload back to BP node to send funding transaction, and then send the payouts.

I'm doing a dry run of this approach today - assuming it goes well...I think this will be the out-of-the box method, barring any strong objections or suggestions for a better method.

**Comment by jrwashburn** [comment]
Final decisions will be added to readme. Full details will be provided in the updated readme with issue 27 is merged. 

Short version is:
mina-pool-payout can be run once to process stakes and blocks, calculate payments, and provide a hash of the payment plan.

Assuming the node operator approves of the payment plan, mina-pool-payout can be run again, providing the -hash HASH of the payment plan, and assuming that the re-calculated plan matches the hash, it will send out the payments automatically.

Running without -hash will simply require access to an archive database and the staking ledger json files (named according to their hash.)

Running with -hash will require the above, but also requires access to a graphql endpoing to query the inferred nonce and to submit the signed transactions.

Signing options continue to support a keypair in the configuration file, or an ephemeral key, but the ephemeral key will be deprecated due to fees, timing issues it will cause, etc.
