### ISSUE TITLE
Reconsider treatment of fees in the payout calculation

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#60]
Can you make it more clear a bit. I remember it should be equal in the long run. If it was favouring locked on how it was doing that.  Wasn't the existing system does the same. What you outlined here?

Also, I have a proposal to just cut out all the fees generated out instead of just the foundation one. My reasoning is I don't believe these fees never reach any significant amount. When there is some high fee like 500 etc. then we will send it back to the owner which mixes up calculation more. :) From the start, I am just suggesting cutting the fees out of the block when they go significantly towards the coinbase because there is always a possibility of 300-500 snark happening on a block. If there is a significant fee increase where snarks are really ending up to something that we had much more competition on snark marketplace which will drive snark prices up and drop the BP's gainfrom it.

_Originally posted by @EmrePiconbello in https://github.com/jrwashburn/mina-pool-payout/issues/58#issuecomment-855887656_

**Comment by jrwashburn** [comment]
@EmrePiconbello I'm separating this out to a new issue where we can clarify further. I'm not sure if you are suggesting that we should simply ignore fees -- which would have the effect of leaving the fees (positive or negative) for the block producer and just payout the pool on the coinbase, regardless of fees. Is that what you mean?

Or do you mean reduce the coinbase by the snark fee amount, and then payout on the remainder? If the snark fees are high (e.g. 500) and their is a MF/O1 delegation, the BP is still required to payout the foundation. Here are a couple of examples, assuming a foundation delegation which is 40% of the pool, and there are unlocked keys for 5% of the pool. These scenarios also ignore pool fees.

1 - "Normal" scenario

Coinbase: 720
Snark Fees: 0.1
Transaction Fees: 0.2
MF/O1 paid: 288
Common paid: 432.1

2 - "Unfair" scenario where current foundation rules hurt the pool
Coinbase: 720
Snark Fees: 500
Transaction Fees: 0.2
MF/O1 paid: 288
Remainder is -67.8 - no payouts should be made?

Are you suggesting in Scenario 1, the Common should be paid 432.0 instead of 432.1?
And what are you suggesting would be best to happen in scenario 2? 

Here is a real example - block 26406:
    "blocks": [
      {
        "blockHeight": 26406,
        "canonical": true,
        "creator": "B62qoRsqqfdfDb3s4nTgTVUQGLep77ZcoKjjWoyxspTn4CEbtBknDek",
        "dateTime": "2021-06-02T06:33:00Z",
        "snarkFees": "556493109432",
        "stateHash": "3NKCYYHBzBSo9qMdEUKkp34m7LY1pZca3h19YBgGriHnDrZbkhux",
        "txFees": "2008242050"
      },

**Comment by jrwashburn** [comment]
A less annoying example - block 29884
https://minaexplorer.com/block/3NK9WXPQW4SwEnBwv2yVyyP73quoBim5RVK26YprghceZ4SjP1kq

"blockHeight": 29884,
"canonical": true,
"snarkFees": "25000000",
 "coinbase": "720000000000",
"txFees": "21000000"
 
This one only goes negative by 0.004, but again, with current payout methods, that may be deducted from the payout.

**Comment by jrwashburn** [comment]
Perhaps the block producer should bear the risk - and reward - for block production.

Meaning there would be no "common" pool - all accounts would be treated just like MF/O1 delegators and would receive their simple pro-rata share of the 720 coinbase, and the unlocked accounts would get their relative pro-rata share of the supercharged 720 coinbase, and the pool operator would simply keep any gains or losses from the block fees for snarks and transactions. 

I think that is probably what Emre is proposing, and given the snark fee issues, this probably makes the most sense.

**Comment by jrwashburn** [comment]
After thinking more about this, the block producer / pool have to be the ones to take the loss -- they are begin compensated for that risk by the 5% of earnings on all the other MF/O1 delegations. I think the best solution is to have the block producer take all risk/reward for fees as suggested above.

**Comment by EmrePiconbello** [comment]
I agree with the update it's going to be a limit for coinbase snark so producers can set their limit and take their risk as they prefer. My only concern was mostly about the small producers getting hit by the random high snark fees since that can cause issues for them while it's not likely it happens from time to time.

**Comment by jrwashburn** [comment]
Closing - will revisit if pool operators request / are really looking for this feature.
