### ISSUE TITLE
Problem with zero commission rate

### ISSUE THREAD

**Issue by fluciotto** [jrwashburn/mina-pool-payout#63]
Hi,

I briefly tested the script, and i encountered a problem: when the commission rate is zero, the retained commision rate is the default value (0.05).
I tested with 0, 0.0, even with double quotes, but i'm stuck with the default commission rate.
If i set the commission rate to 0.00000000001, it works as expected, but this solution is not acceptable.

An idea?

**Comment by jrwashburn** [comment]
Sorry about that - I didn't really expect 0 and had some defaults. They've been removed and replaced with an exception if a valid number is not specified. Thanks!
