### ISSUE TITLE
calculate and output the pool revenue from a given payout run

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#68]
As requested by Nightguy1688#3119 in Discord: https://discord.com/channels/484437221055922177/799597981762453535/866456694540599343

Add logging to show:

Total Coinbase Generated: total block reward
Total User Transaction Fees Generated: fees collected from user transactions
Total Snark Fees Paid: fees paid out for snarks (includes fees from coinbase)
Net Coinbase Received: = Total Coinbase Generated + User Tx Fees - Snark Fees 
Total Payouts Sent: sum of payout amounts
Total Payout Transaction Fees: sum of payout transaction send fees
Net MINA to Pool Operator: + Net Coinbase Received - Total Payouts Sent - Total Payout Transaction Fees

**Comment by vanphandinh** [comment]
> As requested by Nightguy1688#3119 in Discord: https://discord.com/channels/484437221055922177/799597981762453535/866456694540599343
> 
> Add logging to show:
> 
> Total Coinbase Generated: total block reward
> Total User Transaction Fees Generated: fees collected from user transactions
> Total Snark Fees Paid: fees paid out for snarks (includes fees from coinbase)
> Net Coinbase Received: = Total Coinbase Generated - User Tx Fees - Snark Fees
> Total Payouts Sent: sum of payout amounts
> Total Payout Transaction Fees: sum of payout transaction send fees
> Net MINA to Pool Operator: + Net Coinbase Received - Total Payouts Sent - Total Payout Transaction Fees

`Net Coinbase Received: = Total Coinbase Generated - User Tx Fees - Snark Fees` 
it seems it's not correct. you should plus User Tx Fees instead of minus
`Net Coinbase Received: = Total Coinbase Generated + User Tx Fees - Snark Fees`

**Comment by jrwashburn** [comment]
Closed w/ #71
