### ISSUE TITLE
Couldn't send user_command: Error creating user command error

### ISSUE THREAD

**Issue by wjdfx** [jrwashburn/mina-pool-payout#73]
When I used the script, I started reporting errors almost after a few transactions were sent. any suggest?

```message: `Couldn't send user_command: Error creating user command: {"payload":{"common":{"fee":"0.001","fee_token":"1","fee_payer_pk":"B62qiUYxxxxxxx","nonce":"266","valid_until":"4294967295","memo":"E4YzpZRQxxxxx"},"body":["Payment",{"source_pk":"B62xxxxxxx","receiver_pk":"B62qihyyyyyyy","token_id":"1","amount":"7964041225"}]},"signer":"B62qiUYSjLkQuvgouQ1xxx","signature":["Signature","7mXK2mYsQydaoNzzzzzxxxxxMnYwbUkst3vLoix9Xd"]} Error: Input nonce 266 either different from inferred nonce 265 or below minimum_nonce 264`,
    path: [ 'sendPayment' ]```

**Comment by jrwashburn** [comment]
A relatively simple workaround is to use the suppression feature to suppress payments that were successfully made, and re-run the payout to pickup the addresses that failed. See https://github.com/jrwashburn/mina-pool-payout#handling-special-accounts---suppressing-or-redirecting-payouts. Manual control over .paidblocks is also be necessary to re-try the blocks (remove the entries from .paidblocks to re-process. See the final paragraph in readme.

Note that these payments may be re-tried automatically, so it is best to wait some time between runs and double check to be certain which payments failed.

Also, note that if this workaround is used, it is important to remember to remove the keys from the exclusion list for the next full run.
