### ISSUE TITLE
add an option to input epoch number when executing the payout

### ISSUE THREAD

**Issue by lampardlamps** [jrwashburn/mina-pool-payout#75]
Just an idea - as I understand, currently one needs to look for the `-m` and `-x` values when executing the payout programme. For BPs who pays once after epoch ends, it would perhaps be more convenient if one can input the epoch number, and the programme queries the GraphQL with the creator key and epoch number, to get a full list of blocks. In which case no need for `-m` and `-x` inputs, just a `-e` would suffice.

**Comment by lampardlamps** [comment]
Hi Jonathan,
  Thanks for looking into this. I'm not sure I understand questions 1 and
2; my thought was more about block height rather than slot number, and the
starting and ending block heights (your -m and -x inputs) can be obtained
by enquiring graphQL with the epoch number. For 3, I think it's sensible to
throw an error like "the given epoch has not ended yet! try use -m -x
option instead." , and fail, but I can understand the warning message
approach too.
  The idea is just to give BPs who pays after one epoch ends the
convenience.

**Comment by jrwashburn** [comment]
Closed by #88 
When running payout you can now specify -e=[epoch number] to run for the epoch.

**Comment by lampardlamps** [comment]
Awesome, thanks! .
