### ISSUE TITLE
output total/summary json along with transactions

### ISSUE THREAD

**Issue by rfunduk** [jrwashburn/mina-pool-payout#77]
this output info

```
------------------- Summary & Totals ------------------
Calculations based on entire pool
Total Coin Base Generated: X
User Transaction Fees Generated (net of snark fees): X
Total Snark Fees Paid From Coinbase: X
Net Coinbase Received: X
Total Amounts Due To Stakers: X
Total Payout Transaction Fees: X
Net MINA to Pool Operator (after send transaction fees): X
------------------- Summary & Totals ------------------
```

would be very useful to be able to read programmatically along with the `payout_transactions_*.json` and `payout_details_*.json` files. specifically to get the commission/pool operator reward and not have to calculate it from the raw data

would you consider implementing this, or accept a PR of same?

**Comment by jrwashburn** [comment]
Yes, and yes.

**Comment by rfunduk** [comment]
thanks folks 👍
