### ISSUE TITLE
Support for customized pool fees

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#86]
Many pools have specifically negotiated fees for larger delegators. Add support to provide key-specific fees to override the pool default. The override rate would be applied specifically to payouts for that address

Add another configuration file (perhaps .negotiatedFees) to provide public key and override rate in decimal:

B62qkBqSkXgkirtU3n8HJ9YgwHh3vUD6kGJ5ZRkQYGNPeL5xYL2tL1L|0.012573

Anticipate other fee structures / special deals in the future - extracting fee calculation to make it pluggable is a good idea. That would allow forks to do other things like first block is free, or first epoch free for new delegators, or ... etc.

**Comment by vincentreboul** [comment]
Love the idea! Will be really useful for our TowerStake pool.
Being able to offer different fees for 1st epoch would be awesome.
