### ISSUE TITLE
Problem with zero commission rate in .negotiatedFees

### ISSUE THREAD

**Issue by fluciotto** [jrwashburn/mina-pool-payout#89]
Hello,

I just tested the script with a .negotiatedFees file, and i encountered a problem: when the negociated commission rate is zero, the retained commision rate is the default value (COMMISSION_RATE).
If i put 0.00000000000000000000001 as the negociated commission rate in .negotiatedFees, it works well.

**Comment by jrwashburn** [comment]
Will investigate and resolve. I ran across this earlier, but thought it was resolved and could not reproduce again. Will attempt to reproduce.

**Comment by fluciotto** [comment]
The problem seems to come from https://github.com/jrwashburn/mina-pool-payout/blob/ef714da45387f62f650fa4916580f35a55354898/src/core/payoutCalculator/PayoutCalculator.ts#L86.
This line takes the default commision rate if the negotiated commission rate is zero, right?

**Comment by otro34** [comment]
opened pull request to fix.
